### ISSUE TITLE
installatie handleiding mogelijke fout

### ISSUE THREAD

**Issue by V-hofman** [JustFalco/JavaSDBackend#4]
![afbeelding](https://user-images.githubusercontent.com/80648504/169912363-8d8d93ec-3399-443e-9378-4cfb9a4ce86d.png)
draaide het niet op port 8081?

**Comment by JustFalco** [comment]
Klopt inderdaad, dankjewel

**Comment by JustFalco** [comment]
Dit geldt alleen als de applicatie wordt gedraaid in Docker
